Init, Install, Devon e READMEs
HPE-USP-SPIRE/signed-assertions pull request #12
Opened 2024-01-18 17:29 UTC by PedroBarcha

@marques-ma Como boa parte daqui é referente à documentação, estou te colocando como revisor.

### Mudanças
- **Init e .cfg:** Agora só temos um de cada, na raiz do projeto. Ao rodar o init, ele pergunta qual sample você quer usar e já copia o .cfg pros WLs desse sample. O README da raiz foi atualizado de acordo.
- **Script de instalação:**  O script agora clona e compila o "spire-devon" (spire-signed-assertions). O script também pergunta agora o que que o usuário quer instalar (pacotes apt? docker? spire-signed-assertions?) . Agora o script fica na raiz.
- *READMES*: Fiz uma reestruturação bem grande nessa parte. Tinha **muita** coisa repetida e muito README não referenciado (o que é ruim, porque o usuário só olha pro README principal em geral). O README que ficava no `samples` não existe mais, seu conteúdo foi redirecionado pros demais READMES (1 principal  e 1 para cada sample). A ideia é que o README principal faça um overview de cada sample (com ref. para o respectivo README), além de ensinar a configurar o ambiente e a rodar a aplicação. Já os READMEs de cada sample explicam coisas mais técnicas somente (funcionamento do código, fluxo dos tokens, funçao de cada WL etc) e descrevem as respectivas APIs.

### Sugestão de procedimento de revisão
- Revisão geral dos arquivos modificados
- Olhar os 5 READMES (1 principal + 1 para cada sample). Se puder, leia com calma eles, pois mudei muita coisa e acho que algumas mudanças podem não estar hiper claras. Em especial, o README da fase 3 está vazio, pois não soube descrever o funcionamento dele, nem a parte da API. Também não sei se coloquei os endpoints certos no README de cada sample.
- Rodar o `install_dependencies` para baixar o `spire-signed-assertions` (além de testar o script, é necessário ter a nova versão desse repo para poder usar os samples). 
- Rodar o ID e o Anom (os outros 2 samples já testei). Depois,  basta configurar o .cfg na raiz do repo e roda o init de lá.

2024-01-18 23:25 UTC, marques-ma requested changes
Mandou mt bem. O install ficou bem intuitivo e o novo init facilitou muito a vida!  

Finalizando essa PR eu dou mais um tapa no README, mas pelo que li até agora tb tá bem bom.

2024-01-19 13:12 UTC, PedroBarcha commented on .cfg
Sim, deixei um de template (com valores dummy). Acredito que futuros commits não vão modificar ele.

2024-01-19 13:15 UTC, PedroBarcha commented on kill
acho que seria só o spire-signed-assertions. no script de instalação fala o lugar onde ele é instalado. vale apena um scirpt novo ou alterar o existente só pra remover isso?

2024-01-23 14:30 UTC, PedroBarcha commented
@marques-ma Para desisntalar o spire, é so rodar o install_dependencies com -u

2024-01-23 18:24 UTC, marques-ma approved these changes
Maravilha! Parece tudo ok. Vou aprovar e qdo puder faz o merge, que já vou tascar outra PR na sequência  :-D

2024-01-23 23:03 UTC, merged