Optimization phase 1
HPE-USP-SPIRE/signed-assertions pull request #6
Opened 2023-10-26 15:32 UTC by PedroBarcha

Alterações:
- **Otimização das dependências dos WLs**: criação da imagem "common" que baixa as dependências em comum dos WLs. Essa imagem é construída no início do `docker-compose`, daí o dockerfile dos WLs fazem FROM dessa imagem. _Nota: o subject é o único que usa dependências diferentes, mas na prática todos os dockerfiles têm `go mod download`. Isso não afeta o tempo de execução dos demais WLs._ 
- **Otimização do go build**: dockerfile dos WLs foi alterado para verificar se houve modificação em algum dos arquivos que afeta o programa compilado (verificação baseada em hash). Nesse caso, realiza `go build`, caso contrário aproveita o buil/compilado/binário anterior. Para isso, agora existe um diretório `bin`  contendo o compilado, em cada WL. O nome desse binário é o hash dos arquivos utilizados em sua compilação.
- **Init**: voltou! O motivo é que é necessário copiar o compilados dos WLs para o host, e só é possível fazer isso por linha de comando.
- **Scripts de git**: voltaram, pois quebram um galho. Estão na raiz.

2023-10-27 17:18 UTC, PedroBarcha commented
@henriquezanela Se tiver tudo ok, pode deixar que faço o merge

2023-10-30 22:34 UTC, henriquezanela requested changes
@PedroBarcha
Não encontrei o .cfg na raiz do **samples** como descrito, então alterei o .cfg na raiz de cada versão (SVID-NG, phase3).
O INIT dá um erro de não encontrar o start_spire_env.sh (linha 15), mesmo existindo no /opt/spire. Alterei a linha 15 de <./> para <bash> e executou como esperado.
O SVID-NG executou até o final (_deposit_ e _balance_), contudo o phase3 falhou na hora de iniciar a requisição de _deposit_ (famoso conhecido nosso, o ERR_CONNECTION_REFUSED). Não sei se a versão que tu usou do _IDMode_ está desatualizada, mas se rodou contigo, precisamos de outro membro pra checar este possível problema.

2023-11-03 15:04 UTC, pedro-hf-mendes commented
Só um ponto, tá dando conflito parece, nos arquivos cfg, então vai ter que resolver esse conflito. Alguns .cfg q tão dando conflito é pq nessa branch tá com valores, e na main tá tudo vazio. Eu acho mais saudável manter tudo vazio, aí cada um adiciona seus valores e não faz commit deles

2023-11-03 16:51 UTC, pedro-hf-mendes approved these changes

2023-11-03 19:11 UTC, merged